# Generated by Django 4.1.5 on 2023-02-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cpu_motherboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpu',
        ),
        migrations.DeleteModel(
            name='Motherboard',
        ),
    ]
